export const inmuebles = [
    {
          idanfitrion:"1",
            tipopropiedad:"1",
            tituloanuncio:"Hab-1",
            descripcion:"habitacion en CBBA, NO SE PERMITEN NIÑOS NI MASCOTAS",
            ubicacion:"Cochabamba",
            precio:"65BS",
            capacidad:"2",
            habitaciones:"2",
            baños:"1",
            camas:"1",
            niños:"0",
            normas:"2",
            mascotas:"0",
            qr:"NOHAY"
}
   ,
    {
        idanfitrion:"1",
            tipopropiedad:"1",
            tituloanuncio:"Hab-2",
            descripcion:"habitacion en CBBA,SE PERMITEN NIÑOS, NO MASCOTAS",
            ubicacion:"Cochabamba",
            precio:"65BS",
            capacidad:"2",
            habitaciones:"2",
            baños:"1",
            camas:"1",
            niños:"1",
            normas:"2",
            mascotas:"0",
            qr:"NOHAY"
    },
    {
        idanfitrion:"1",
            tipopropiedad:"1",
            tituloanuncio:"Hab-3",
            descripcion:"habitacion en CBBA,SE PERMITEN NIÑOS y MASCOTAS",
            ubicacion:"Cochabamba",
            precio:"65BS",
            capacidad:"2",
            habitaciones:"2",
            baños:"1",
            camas:"1",
            niños:"1",
            normas:"2",
            mascotas:"1",
            qr:"NOHAY"
    },
    {
        idanfitrion:"1",
            tipopropiedad:"1",
            tituloanuncio:"Hab-5",
            descripcion:"habitacion en SC,SE PERMITEN NIÑOS, NO MASCOTAS",
            ubicacion:"Santa Cruz",
            precio:"65BS",
            capacidad:"2",
            habitaciones:"2",
            baños:"1",
            camas:"1",
            niños:"1",
            normas:"2",
            mascotas:"0",
            qr:"NOHAY"
    },
    {
        idanfitrion:"1",
            tipopropiedad:"1",
            tituloanuncio:"Hab-6",
            descripcion:"habitacion en SC,NO PERMITEN NIÑOS, NO MASCOTAS",
            ubicacion:"Santa Cruz",
            precio:"65BS",
            capacidad:"2",
            habitaciones:"2",
            baños:"1",
            camas:"1",
            niños:"0",
            normas:"2",
            mascotas:"0",
            qr:"NOHAY"
    }
]